name = "greenput-api"
main = "../../dist/apps/greenput-api/index.js"
compatibility_date = "2024-01-01"

[[d1_databases]]
binding = "DB"
database_name = "greenput-prod-db"
database_id = "env_var_will_override_this"

# Local dev fallback
[env.dev]
d1_databases = [
  { binding = "DB", database_name = "greenput-dev-db", database_id = "XXXX" }
]
