name: Release

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      first_release:
        description: 'First Release (skip tag check)'
        required: false
        type: boolean
        default: false

permissions:
  contents: write # to be able to publish a GitHub release
  issues: write # to be able to comment on released issues
  pull-requests: write # to be able to comment on released pull requests
  id-token: write # to enable use of OIDC for npm provenance
  packages: write # to be able to publish to GitHub Packages

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js and .npmrc
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: 'https://npm.pkg.github.com'
          scope: '@basenative'

      - name: Install dependencies
        run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure Git
        run: |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

      - name: Release
        run: |
          # Check if there are any tags to determine if it's a first release
          if git describe --tags --abbrev=0 > /dev/null 2>&1; then
            echo "Existing tags found. Running standard release."
            npx nx release --skip-publish
          else
            echo "No tags found. Running first release."
            npx nx release --first-release --skip-publish
          fi

          # Explicitly publish packages
          npx nx release publish --yes --registry=https://npm.pkg.github.com/
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_CONFIG_REGISTRY: 'https://npm.pkg.github.com'
